name: Achievement-Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2

      - name: Project Directory Permissions
        run: chmod -R 777 ./*

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Copy .env.example.testing
        run: php -r "file_exists('.env.example.testing') || copy('.env.example', '.env.example.testing');"

      - name: Install Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: create DB and schema
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Generate key
        run: php artisan key:generate

      - name: Generate jwt secret for testing
        run: php artisan jwt:secret --env=testing

      - name: Execute tests Feature tests via PHPUnit
        run: php artisan test
